/**
 * GitHub Profile README Compiler
 * 
 * Stitches modular Markdown files from /sections into a unified, high-performance,
 * developer-focused README.md in the root directory.
 * 
 * Usage:
 *   node scripts/generate-readme.js
 */

const fs = require('fs');
const path = require('path');

// Target order of profile sections
const SECTION_ORDER = [
  'hero.md',
  'about.md',
  'dashboard.md'
];

const SECTIONS_DIR = path.join(__dirname, '..', 'sections');
const OUTPUT_FILE = path.join(__dirname, '..', 'README.md');

function compileReadme() {
  console.log('\x1b[35m%s\x1b[0m', 'Initializing GitHub README Compiler...');
  
  let combinedContent = '';

  // Top header notice
  combinedContent += `<!-- \n  ======================================================================\n  WARNING: THIS FILE IS GENERATED AUTOMATICALLY.\n  DO NOT EDIT THIS FILE DIRECTLY.\n  \n  To make changes, please edit the respective files under the "/sections" \n  directory, then compile by running: \n    node scripts/generate-readme.js\n  ======================================================================\n-->\n\n`;

  for (const filename of SECTION_ORDER) {
    const filePath = path.join(SECTIONS_DIR, filename);
    const sectionName = path.basename(filename, '.md').toUpperCase();

    if (!fs.existsSync(filePath)) {
      console.warn('\x1b[33m%s\x1b[0m', `[Warning] File not found: ${filePath}. Skipping.`);
      continue;
    }

    console.log('\x1b[36m%s\x1b[0m', ` Stitched section: ${filename}`);

    const rawContent = fs.readFileSync(filePath, 'utf8');

    // Add boundaries for clean rendering structure and easy troubleshooting
    combinedContent += `<!-- SECTION: START - ${sectionName} -->\n`;
    combinedContent += rawContent.trim();
    combinedContent += `\n<!-- SECTION: END - ${sectionName} -->\n\n`;
  }

  // Write compiled content
  try {
    fs.writeFileSync(OUTPUT_FILE, combinedContent, 'utf8');
    console.log('\x1b[32m%s\x1b[0m', `\n✔ Successfully compiled ${SECTION_ORDER.length} sections into root README.md!`);
  } catch (error) {
    console.error('\x1b[31m%s\x1b[0m', `[Error] Failed to write README.md: ${error.message}`);
    process.exit(1);
  }
}

compileReadme();
